# Generated by Django 4.2.6 on 2023-10-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_connected_habit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-id']},
        ),
    ]
