# Generated by Django 4.2.6 on 2023-10-09 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='connected_habit',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_satisfying': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit'),
        ),
    ]
